import { NextResponse } from 'next/server';
import { query } from '@/lib/db';
import { fetchOgName } from '@/lib/og-name';

export const runtime = 'nodejs';
export const maxDuration = 300;

// Simple slug-like name detector: no spaces, all lowercase, looks like a hostname/slug
function isAutoGeneratedName(name: string): boolean {
  return /^[a-z0-9][a-z0-9.\-]+$/.test(name) && !name.includes(' ');
}

export async function POST(request: Request) {
  const { searchParams } = new URL(request.url);
  if (searchParams.get('secret') !== process.env.ADMIN_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Fetch all rows ordered by scored_at desc (most recent first)
  let rows: { slug: string; name: string; docs_url: string; scored_at: string }[];
  try {
    const res = await query<{ slug: string; name: string; docs_url: string; scored_at: string }>(
      `SELECT slug, name, docs_url, scored_at FROM public.scores ORDER BY scored_at DESC`
    );
    rows = res.rows;
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }

  // Dedupe by normalized docs_url — keep most recent (first in desc order)
  const seen = new Set<string>();
  const toDelete: string[] = [];

  for (const row of rows) {
    const normalized = (row.docs_url || '').toLowerCase().replace(/\/+$/, '');
    if (seen.has(normalized)) {
      toDelete.push(row.slug);
    } else {
      seen.add(normalized);
    }
  }

  // Delete duplicates
  if (toDelete.length) {
    await query(`DELETE FROM public.scores WHERE slug = ANY($1)`, [toDelete]);
  }

  // Re-fetch OG names for auto-generated names (slug-like, no spaces)
  const nameUpdates: { slug: string; from: string; to: string }[] = [];
  const remaining = rows.filter(r => !toDelete.includes(r.slug));

  for (const row of remaining) {
    if (isAutoGeneratedName(row.name)) {
      const ogName = await fetchOgName(row.docs_url);
      if (ogName && ogName !== row.name && ogName.length > 1) {
        await query(`UPDATE public.scores SET name = $1 WHERE slug = $2`, [ogName, row.slug]);
        nameUpdates.push({ slug: row.slug, from: row.name, to: ogName });
      }
    }
  }

  return NextResponse.json({
    deduped: toDelete.length,
    deleted: toDelete,
    nameUpdates,
  });
}
