import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { fetchOgName } from '@/lib/og-name';

export const runtime = 'nodejs';
export const maxDuration = 300;

// Simple slug-like name detector: no spaces, all lowercase, looks like a hostname/slug
function isAutoGeneratedName(name: string): boolean {
  return /^[a-z0-9][a-z0-9.\-]+$/.test(name) && !name.includes(' ');
}

export async function POST(request: Request) {
  const { searchParams } = new URL(request.url);
  if (searchParams.get('secret') !== process.env.ADMIN_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SECRET_KEY!
  );

  // Fetch all rows ordered by scored_at desc (most recent first)
  const { data: rows, error } = await supabase
    .from('scores')
    .select('slug, name, docs_url, scored_at')
    .order('scored_at', { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  // Dedupe by normalized docs_url — keep most recent (first in desc order)
  const seen = new Set<string>();
  const toDelete: string[] = [];

  for (const row of rows) {
    const normalized = (row.docs_url || '').toLowerCase().replace(/\/+$/, '');
    if (seen.has(normalized)) {
      toDelete.push(row.slug);
    } else {
      seen.add(normalized);
    }
  }

  // Delete duplicates
  for (const slug of toDelete) {
    await supabase.from('scores').delete().eq('slug', slug);
  }

  // Re-fetch OG names for auto-generated names (slug-like, no spaces)
  const nameUpdates: { slug: string; from: string; to: string }[] = [];
  const remaining = rows.filter(r => !toDelete.includes(r.slug));

  for (const row of remaining) {
    if (isAutoGeneratedName(row.name)) {
      const ogName = await fetchOgName(row.docs_url);
      if (ogName && ogName !== row.name && ogName.length > 1) {
        await supabase.from('scores').update({ name: ogName }).eq('slug', row.slug);
        nameUpdates.push({ slug: row.slug, from: row.name, to: ogName });
      }
    }
  }

  return NextResponse.json({
    deduped: toDelete.length,
    deleted: toDelete,
    nameUpdates,
  });
}
